docker-compose.yml
version: '3.0'
services:
  jenkins:
   image: jenkins/jenkins:2.235.3-lts-centos7
   container_name: my_jenkins
   privileged: true
   user: root
   ports:
      - 8080:8080
      - 50000:50000
   volumes:
      - /var/jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/user/local/bon/docker
   restart: always

  sonarqube:
   image: sonarqube:lts
   container_name: my_sonar
#   privileged: true
#   user: root
   ports:
      - 9000:9000
      - 9092:9092
   environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
   depends_on:
     - postgres
   restart: always

  postgres:
   image: postgres:9.6
   container_name: my_postgree
   environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
   volumes:
      - "/var/postgres-data:/var/lib/postgresql/data"
   restart: always